[project]
name = "uv-lib"
version = "0.1.0"
description = "A uv library for Python"
readme = "README.md"
authors = [
    { name = "yasuomaidana"}
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
