[package]
name = "blkrust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.30", features = ["derive", "env"] }
env_logger = "0.11.6"
log = "0.4.26"
serde_json = "1.0.138"
