# Use the official Rust image as a base
FROM rust:1-alpine3.19

# Install necessary dependencies
RUN apk add --no-cache \
    build-base \
#     openssl-dev \
    util-linux
    
RUN rustup default stable 
# RUN rustup target add x86_64-unknown-linux-musl

# Set the working directory
WORKDIR /usr/src/app

# Copy the Cargo.toml and Cargo.lock files
# COPY Cargo.toml Cargo.lock ./

# Copy the source code
# COPY . .